// Open ?profile=1, click '.markdown-body>h2' to allow audio, then eval --stdin this file.
(async () => {
  const $ = id => document.getElementById(id);
  const assert = (value, message) => { if (!value) throw Error(message); };
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const key = (key, repeat = false) => document.activeElement.dispatchEvent(new KeyboardEvent('keydown', { key, code: key, repeat, bubbles: true, cancelable: true }));
  const audio = { contexts: [], tones: 0, menu: 0, selections: 0 };
  const NativeAudioContext = window.AudioContext;
  window.AudioContext = class extends NativeAudioContext {
    constructor() { super(); audio.contexts.push(this); }
    createOscillator() {
      const oscillator = super.createOscillator();
      const set = oscillator.frequency.setValueAtTime.bind(oscillator.frequency);
      oscillator.frequency.setValueAtTime = (value, time) => {
        if (value === 740) audio.menu++;
        else if (value === 880) audio.selections++;
        else audio.tones++;
        return set(value, time);
      };
      return oscillator;
    }
  };
  const preview = $('preview-art').textContent;
  await wait(400);
  assert($('preview-art').textContent !== preview, 'Attract-mode preview does not animate');
  $('settings-open').click();
  assert(!$('game-settings').hidden && $('game-cover').inert, 'Settings did not open in the card');
  assert(document.querySelectorAll('input[name="ship"]').length === 4, 'Ship choices missing');
  key('ArrowDown');
  assert(document.activeElement === $('audio-tab') && $('audio-panel').hidden, 'Down should focus Audio without selecting it');
  key('Enter');
  assert(!$('audio-panel').hidden && document.activeElement === $('music-enabled'), 'Enter should open Audio and focus Music');
  const music = $('music-enabled').checked;
  key('Enter');
  assert($('music-enabled').checked !== music, 'Enter should toggle Music');
  key('Enter', true);
  assert($('music-enabled').checked !== music, 'Held Enter toggled Music again');
  key('Enter');
  key('ArrowDown');
  assert(document.activeElement === $('sfx-enabled'), 'Down should focus Sound effects');
  key('Enter'); key('Enter');
  key('ArrowDown');
  assert(document.activeElement === $('settings-close'), 'Down should reach Done');
  key('ArrowDown');
  assert(document.activeElement === $('ship-tab'), 'Settings navigation should wrap to Ship');
  key('Enter');
  const firstShip = document.activeElement;
  key('ArrowDown');
  assert(document.activeElement.value === '1', 'Down should focus the next ship');
  key('ArrowUp');
  assert(document.activeElement === firstShip, 'Up should focus the previous ship');
  key('ArrowDown'); key('Enter');
  assert(JSON.parse(localStorage.getItem('space-invaders-settings')).ship === 1, 'Enter should select and save the focused ship');
  await wait(80);
  const selectedShip = document.activeElement;
  const beforeCycling = audio.menu;
  const beforeSelection = audio.selections;
  for (const arrow of ['ArrowRight', 'ArrowDown', 'ArrowUp', 'ArrowLeft']) {
    key(arrow);
    await wait(80);
    assert(selectedShip.checked && JSON.parse(localStorage.getItem('space-invaders-settings')).ship === 1, 'Cycling should not change the selected ship');
    assert(getComputedStyle(selectedShip.parentElement).color === 'rgb(173, 240, 192)', 'Chosen ship should stay green while cycling');
  }
  assert(audio.menu === beforeCycling + 4, 'Each arrow movement should play a cycling cue');
  assert(audio.selections === beforeSelection, 'Browsing ships should not play a confirmation');
  key('Enter');
  assert(audio.selections === beforeSelection + 1, 'Enter should confirm even an already-selected ship');
  key('Enter', true);
  assert(audio.selections === beforeSelection + 1, 'Held Enter should not repeat confirmation sounds');
  assert(document.querySelector('.settings-help').textContent.startsWith('use arrow keys'), 'Settings hint should mention all arrow keys');
  document.querySelector('input[name="ship"][value="2"]').click();
  assert(JSON.parse(localStorage.getItem('space-invaders-settings')).ship === 2, 'Ship preference was not saved');
  assert(audio.selections === beforeSelection + 2, 'Click should play one confirmation sound');
  assert(!selectedShip.checked && getComputedStyle(selectedShip.parentElement).color !== 'rgb(173, 240, 192)', 'Old ship should lose its green selection');
  $('ship-tab').dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  assert($('audio-tab').getAttribute('aria-selected') === 'true' && !$('audio-panel').hidden, 'Settings tab keyboard navigation failed');
  for (const id of ['music-enabled', 'sfx-enabled']) {
    if ($(id).checked) $(id).click();
    $(id).click();
  }
  await wait(60);
  assert(audio.contexts.length === 1, 'Sound settings should share one audio context');
  assert(audio.contexts[0].state === 'running', 'Audio did not unlock after interaction');
  assert(audio.tones === 0, 'Audio must stay quiet on the profile');
  assert(audio.menu > 0, 'Changing settings should play a navigation cue');
  $('settings-close').click();
  $('enter').click();
  $('profile-scene').getAnimations()[0]?.finish();
  await wait(2100);
  assert(!$('overlay').hidden && $('game-shell').dataset.mode === 'ready', 'Boot did not stop at the title');
  assert(audio.tones === 0, 'Game audio started before Play');
  const beforeMenu = audio.menu;
  $('play').dispatchEvent(new KeyboardEvent('keydown', { code: 'ArrowDown', bubbles: true }));
  await wait(80);
  assert(audio.menu === beforeMenu + 1, 'Keyboard cycling should play one menu tick');
  $('menu-settings').firstElementChild.dispatchEvent(new PointerEvent('pointerover', { pointerType: 'mouse', relatedTarget: $('menu-settings'), bubbles: true }));
  await wait(80);
  assert(audio.menu === beforeMenu + 1, 'Moving within one option played another tick');
  const profileLink = document.querySelector('.work a');
  profileLink.dispatchEvent(new PointerEvent('pointerover', { pointerType: 'mouse', bubbles: true }));
  await wait(80);
  assert(audio.menu === beforeMenu + 2, 'Profile hover should play a tick outside gameplay');
  $('settings-open').disabled = true;
  $('settings-open').dispatchEvent(new PointerEvent('pointerover', { pointerType: 'mouse', bubbles: true }));
  await wait(80);
  assert(audio.menu === beforeMenu + 2, 'Disabled controls should stay silent');
  $('settings-open').disabled = false;
  $('menu-settings').click();
  key('Home');
  assert(document.body.dataset.view === 'game', 'Settings Home key scrolled out of the game');
  key('Escape');
  assert($('game-settings').hidden && document.activeElement === $('play') && document.body.dataset.view === 'game', 'Esc should return to Play on the title without zooming out');
  key('Escape', true);
  assert(document.body.dataset.view === 'game', 'Held Esc zoomed out after closing Settings');
  $('play').click();
  assert($('overlay').hidden, 'Game failed to launch');
  assert(audio.tones > 0, 'Enabled music did not play');
  $('settings-open').click();
  const paused = audio.tones;
  await wait(220);
  assert(audio.tones === paused, 'Opening settings did not stop music');
  $('music-enabled').click();
  $('settings-close').click();
  const beforeShot = audio.tones;
  $('game').dispatchEvent(new KeyboardEvent('keydown', { code: 'Space', bubbles: true }));
  await wait(300);
  $('game').dispatchEvent(new KeyboardEvent('keyup', { code: 'Space', bubbles: true }));
  assert(audio.tones > beforeShot, 'Enabled sound effects did not play');
  $('settings-open').click();
  $('sfx-enabled').click();
  $('settings-close').click();
  const muted = audio.tones;
  $('game').dispatchEvent(new KeyboardEvent('keydown', { code: 'Space', bubbles: true }));
  await wait(300);
  $('game').dispatchEvent(new KeyboardEvent('keyup', { code: 'Space', bubbles: true }));
  assert(audio.tones === muted, 'Muted audio still generated sound');
  const mutedMenu = audio.menu;
  profileLink.dispatchEvent(new PointerEvent('pointerover', { pointerType: 'mouse', bubbles: true }));
  await wait(80);
  assert(audio.menu === mutedMenu, 'SFX mute did not silence navigation cues');
  $('pause').click();
  assert($('game-shell').dataset.mode === 'paused' && $('detail').hidden && $('play').hidden && $('pause').hidden, 'Pause screen contains removed controls or copy');
  $('game').dispatchEvent(new KeyboardEvent('keydown', { code: 'KeyP', bubbles: true }));
  assert($('game-shell').dataset.mode === 'playing', 'P did not unpause');
  $('settings-open').click();
  $('ship-tab').click();
  const selectedBeforeMute = audio.selections;
  document.querySelector('input[name="ship"][value="2"]').click();
  assert(audio.selections === selectedBeforeMute, 'SFX mute should silence ship confirmations');
  key('Escape');
  assert($('game-shell').dataset.mode === 'ready' && document.activeElement === $('play'), 'Esc during a round should return to the title, not resume gameplay');
  $('play').click();
  assert($('game-shell').dataset.mode === 'playing', 'Play should work after escaping Settings');
  $('profile-view').click();
  $('profile-scene').getAnimations()[0]?.finish();
  await wait(60);
  assert(!$('game-cover').hidden && $('game-console').hidden, 'Return should restore the shooting preview');
  assert(audio.contexts.length === 1, 'Settings leaked audio contexts');
  window.AudioContext = NativeAudioContext;
  return 'Passed: Settings arrows/Enter/Esc, preview, saved preferences, navigation audio, mute, pause, and profile return.';
})()
